/*
 * GWMS Public API
 * GWMS（仓库管理系统）的官方公开API。 它为ERP、电子商务平台和TMS等外部系统提供了一个标准化、健壮且易于集成的接口，以便与WMS功能进行交互。  ## 认证机制  本API采用基于JWT的Bearer令牌认证，结合三重凭证验证机制：  1. **客户端凭证（Client Credentials）**：由系统管理员为上游系统生成的clientId和clientSecret 2. **API密钥（API Key）**：由仓库用户生成，关联到特定仓库和权限范围 3. **访问令牌（Access Token）**：通过认证端点获取的JWT令牌，用于API访问  ## 快速开始  1. **获取凭证**：联系系统管理员获取clientId和clientSecret，联系仓库用户获取apiKey 2. **获取令牌**：调用 `POST /auth-api/token` 端点获取访问令牌 3. **调用API**：在请求头中添加 `Authorization: Bearer {access_token}` 调用其他API  ## 认证头部格式  所有API请求（除了认证端点）必须包含以下HTTP头部：  ``` Authorization: Bearer {access_token} ```  其中`{access_token}`是从认证端点获取的JWT令牌。缺少此头部或令牌无效将导致401错误。  ## 权限范围  API访问权限基于以下范围进行控制：  | 权限范围 | 描述 | 适用API | 示例操作 | |---------|------|---------|---------| | `product:read` | 产品数据读取权限 | `/api/v1/products/_*` | 查询产品列表、获取产品详情 | | `product:write` | 产品数据写入权限 | `/api/v1/products/_*` | 创建产品、更新产品信息 | | `warehouse:read` | 仓库数据读取权限 | `/api/v1/warehouses/_*` | 查询仓库列表、获取仓库详情 | | `warehouse:write` | 仓库数据写入权限 | `/api/v1/warehouses/_*` | 创建仓库、更新仓库信息 | | `stock:read` | 库存数据读取权限 | `/api/v1/stock/_*` | 查询库存数量、库存明细 | | `stock:write` | 库存数据写入权限 | `/api/v1/stock/_*` | 库存调整、库存转移 | | `inbound:read` | 入库单读取权限 | `/api/v1/inbound/_*` | 查询入库单列表、获取入库单详情 | | `inbound:write` | 入库单写入权限 | `/api/v1/inbound/_*` | 创建入库单、更新入库单 | | `outbound:read` | 出库单读取权限 | `/api/v1/outbound/_*` | 查询出库单列表、获取出库单详情 | | `outbound:write` | 出库单写入权限 | `/api/v1/outbound/_*` | 创建出库单、更新出库单 | | `express:read` | 物流渠道读取权限 | `/api/v1/expressChannel/_*` | 查询物流渠道列表 | | `express:write` | 物流渠道写入权限 | `/api/v1/expressChannel/_*` | 创建物流渠道、更新物流渠道 |  ## 错误响应  认证失败时，API将返回以下错误响应：  - **401 Unauthorized**：令牌无效、过期或缺失 - **403 Forbidden**：令牌有效但权限不足 - **429 Too Many Requests**：超过访问频率限制  详细的错误响应格式请参考错误响应部分。 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: api-support@jmalltech.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.jmalltech.gwms.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.jmalltech.gwms.sdk.invoker.JSON;

/**
 * 产品尺寸信息。
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Dimensions implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_LENGTH_CM = "lengthCm";
  @SerializedName(SERIALIZED_NAME_LENGTH_CM)
  private Double lengthCm;

  public static final String SERIALIZED_NAME_WIDTH_CM = "widthCm";
  @SerializedName(SERIALIZED_NAME_WIDTH_CM)
  private Double widthCm;

  public static final String SERIALIZED_NAME_HEIGHT_CM = "heightCm";
  @SerializedName(SERIALIZED_NAME_HEIGHT_CM)
  private Double heightCm;

  public static final String SERIALIZED_NAME_LENGTH_INCH = "lengthInch";
  @SerializedName(SERIALIZED_NAME_LENGTH_INCH)
  private Double lengthInch;

  public static final String SERIALIZED_NAME_WIDTH_INCH = "widthInch";
  @SerializedName(SERIALIZED_NAME_WIDTH_INCH)
  private Double widthInch;

  public static final String SERIALIZED_NAME_HEIGHT_INCH = "heightInch";
  @SerializedName(SERIALIZED_NAME_HEIGHT_INCH)
  private Double heightInch;

  public static final String SERIALIZED_NAME_METRIC_VOLUME = "metricVolume";
  @SerializedName(SERIALIZED_NAME_METRIC_VOLUME)
  private Double metricVolume;

  public static final String SERIALIZED_NAME_IMPERIAL_VOLUME = "imperialVolume";
  @SerializedName(SERIALIZED_NAME_IMPERIAL_VOLUME)
  private Double imperialVolume;

  public Dimensions() {
  }

  public Dimensions lengthCm(Double lengthCm) {
    this.lengthCm = lengthCm;
    return this;
  }

   /**
   * 长度（厘米）。
   * minimum: 0
   * maximum: 10000
   * @return lengthCm
  **/
  @javax.annotation.Nullable
 @DecimalMin("0") @DecimalMax("10000")
  public Double getLengthCm() {
    return lengthCm;
  }

  public void setLengthCm(Double lengthCm) {
    this.lengthCm = lengthCm;
  }


  public Dimensions widthCm(Double widthCm) {
    this.widthCm = widthCm;
    return this;
  }

   /**
   * 宽度（厘米）。
   * minimum: 0
   * maximum: 10000
   * @return widthCm
  **/
  @javax.annotation.Nullable
 @DecimalMin("0") @DecimalMax("10000")
  public Double getWidthCm() {
    return widthCm;
  }

  public void setWidthCm(Double widthCm) {
    this.widthCm = widthCm;
  }


  public Dimensions heightCm(Double heightCm) {
    this.heightCm = heightCm;
    return this;
  }

   /**
   * 高度（厘米）。
   * minimum: 0
   * maximum: 10000
   * @return heightCm
  **/
  @javax.annotation.Nullable
 @DecimalMin("0") @DecimalMax("10000")
  public Double getHeightCm() {
    return heightCm;
  }

  public void setHeightCm(Double heightCm) {
    this.heightCm = heightCm;
  }


  public Dimensions lengthInch(Double lengthInch) {
    this.lengthInch = lengthInch;
    return this;
  }

   /**
   * 长度（英寸）。
   * minimum: 0
   * maximum: 10000
   * @return lengthInch
  **/
  @javax.annotation.Nullable
 @DecimalMin("0") @DecimalMax("10000")
  public Double getLengthInch() {
    return lengthInch;
  }

  public void setLengthInch(Double lengthInch) {
    this.lengthInch = lengthInch;
  }


  public Dimensions widthInch(Double widthInch) {
    this.widthInch = widthInch;
    return this;
  }

   /**
   * 宽度（英寸）。
   * minimum: 0
   * maximum: 10000
   * @return widthInch
  **/
  @javax.annotation.Nullable
 @DecimalMin("0") @DecimalMax("10000")
  public Double getWidthInch() {
    return widthInch;
  }

  public void setWidthInch(Double widthInch) {
    this.widthInch = widthInch;
  }


  public Dimensions heightInch(Double heightInch) {
    this.heightInch = heightInch;
    return this;
  }

   /**
   * 高度（英寸）。
   * minimum: 0
   * maximum: 10000
   * @return heightInch
  **/
  @javax.annotation.Nullable
 @DecimalMin("0") @DecimalMax("10000")
  public Double getHeightInch() {
    return heightInch;
  }

  public void setHeightInch(Double heightInch) {
    this.heightInch = heightInch;
  }


  public Dimensions metricVolume(Double metricVolume) {
    this.metricVolume = metricVolume;
    return this;
  }

   /**
   * 公制体积（立方厘米）。
   * minimum: 0
   * @return metricVolume
  **/
  @javax.annotation.Nullable
 @DecimalMin("0")
  public Double getMetricVolume() {
    return metricVolume;
  }

  public void setMetricVolume(Double metricVolume) {
    this.metricVolume = metricVolume;
  }


  public Dimensions imperialVolume(Double imperialVolume) {
    this.imperialVolume = imperialVolume;
    return this;
  }

   /**
   * 英制体积（立方英寸）。
   * minimum: 0
   * @return imperialVolume
  **/
  @javax.annotation.Nullable
 @DecimalMin("0")
  public Double getImperialVolume() {
    return imperialVolume;
  }

  public void setImperialVolume(Double imperialVolume) {
    this.imperialVolume = imperialVolume;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Dimensions dimensions = (Dimensions) o;
    return Objects.equals(this.lengthCm, dimensions.lengthCm) &&
        Objects.equals(this.widthCm, dimensions.widthCm) &&
        Objects.equals(this.heightCm, dimensions.heightCm) &&
        Objects.equals(this.lengthInch, dimensions.lengthInch) &&
        Objects.equals(this.widthInch, dimensions.widthInch) &&
        Objects.equals(this.heightInch, dimensions.heightInch) &&
        Objects.equals(this.metricVolume, dimensions.metricVolume) &&
        Objects.equals(this.imperialVolume, dimensions.imperialVolume);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lengthCm, widthCm, heightCm, lengthInch, widthInch, heightInch, metricVolume, imperialVolume);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Dimensions {\n");
    sb.append("    lengthCm: ").append(toIndentedString(lengthCm)).append("\n");
    sb.append("    widthCm: ").append(toIndentedString(widthCm)).append("\n");
    sb.append("    heightCm: ").append(toIndentedString(heightCm)).append("\n");
    sb.append("    lengthInch: ").append(toIndentedString(lengthInch)).append("\n");
    sb.append("    widthInch: ").append(toIndentedString(widthInch)).append("\n");
    sb.append("    heightInch: ").append(toIndentedString(heightInch)).append("\n");
    sb.append("    metricVolume: ").append(toIndentedString(metricVolume)).append("\n");
    sb.append("    imperialVolume: ").append(toIndentedString(imperialVolume)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("lengthCm");
    openapiFields.add("widthCm");
    openapiFields.add("heightCm");
    openapiFields.add("lengthInch");
    openapiFields.add("widthInch");
    openapiFields.add("heightInch");
    openapiFields.add("metricVolume");
    openapiFields.add("imperialVolume");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to Dimensions
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Dimensions.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Dimensions is not found in the empty JSON string", Dimensions.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Dimensions.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Dimensions` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Dimensions.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Dimensions' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Dimensions> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Dimensions.class));

       return (TypeAdapter<T>) new TypeAdapter<Dimensions>() {
           @Override
           public void write(JsonWriter out, Dimensions value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Dimensions read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Dimensions given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Dimensions
  * @throws IOException if the JSON string is invalid with respect to Dimensions
  */
  public static Dimensions fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Dimensions.class);
  }

 /**
  * Convert an instance of Dimensions to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

