/*
 * GWMS Public API
 * GWMS（仓库管理系统）的官方公开API。 它为ERP、电子商务平台和TMS等外部系统提供了一个标准化、健壮且易于集成的接口，以便与WMS功能进行交互。  ## 认证机制  本API采用基于JWT的Bearer令牌认证，结合三重凭证验证机制：  1. **客户端凭证（Client Credentials）**：由系统管理员为上游系统生成的clientId和clientSecret 2. **API密钥（API Key）**：由仓库用户生成，关联到特定仓库和权限范围 3. **访问令牌（Access Token）**：通过认证端点获取的JWT令牌，用于API访问  ## 快速开始  1. **获取凭证**：联系系统管理员获取clientId和clientSecret，联系仓库用户获取apiKey 2. **获取令牌**：调用 `POST /auth-api/token` 端点获取访问令牌 3. **调用API**：在请求头中添加 `Authorization: Bearer {access_token}` 调用其他API  ## 认证头部格式  所有API请求（除了认证端点）必须包含以下HTTP头部：  ``` Authorization: Bearer {access_token} ```  其中`{access_token}`是从认证端点获取的JWT令牌。缺少此头部或令牌无效将导致401错误。  ## 权限范围  API访问权限基于以下范围进行控制：  | 权限范围 | 描述 | 适用API | 示例操作 | |---------|------|---------|---------| | `product:read` | 产品数据读取权限 | `/api/v1/products/_*` | 查询产品列表、获取产品详情 | | `product:write` | 产品数据写入权限 | `/api/v1/products/_*` | 创建产品、更新产品信息 | | `warehouse:read` | 仓库数据读取权限 | `/api/v1/warehouses/_*` | 查询仓库列表、获取仓库详情 | | `warehouse:write` | 仓库数据写入权限 | `/api/v1/warehouses/_*` | 创建仓库、更新仓库信息 | | `stock:read` | 库存数据读取权限 | `/api/v1/stock/_*` | 查询库存数量、库存明细 | | `stock:write` | 库存数据写入权限 | `/api/v1/stock/_*` | 库存调整、库存转移 | | `inbound:read` | 入库单读取权限 | `/api/v1/inbound/_*` | 查询入库单列表、获取入库单详情 | | `inbound:write` | 入库单写入权限 | `/api/v1/inbound/_*` | 创建入库单、更新入库单 | | `outbound:read` | 出库单读取权限 | `/api/v1/outbound/_*` | 查询出库单列表、获取出库单详情 | | `outbound:write` | 出库单写入权限 | `/api/v1/outbound/_*` | 创建出库单、更新出库单 | | `express:read` | 物流渠道读取权限 | `/api/v1/expressChannel/_*` | 查询物流渠道列表 | | `express:write` | 物流渠道写入权限 | `/api/v1/expressChannel/_*` | 创建物流渠道、更新物流渠道 |  ## 错误响应  认证失败时，API将返回以下错误响应：  - **401 Unauthorized**：令牌无效、过期或缺失 - **403 Forbidden**：令牌有效但权限不足 - **429 Too Many Requests**：超过访问频率限制  详细的错误响应格式请参考错误响应部分。 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: api-support@jmalltech.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.jmalltech.gwms.sdk.api;

import com.jmalltech.gwms.sdk.invoker.ApiCallback;
import com.jmalltech.gwms.sdk.invoker.ApiClient;
import com.jmalltech.gwms.sdk.invoker.ApiException;
import com.jmalltech.gwms.sdk.invoker.ApiResponse;
import com.jmalltech.gwms.sdk.invoker.Configuration;
import com.jmalltech.gwms.sdk.invoker.Pair;
import com.jmalltech.gwms.sdk.invoker.ProgressRequestBody;
import com.jmalltech.gwms.sdk.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;

import javax.validation.constraints.*;
import javax.validation.Valid;

import com.jmalltech.gwms.sdk.model.ApiErrorResponse;
import com.jmalltech.gwms.sdk.model.EntityStatus;
import com.jmalltech.gwms.sdk.model.LocationCreateRequest;
import com.jmalltech.gwms.sdk.model.LocationListResponse;
import com.jmalltech.gwms.sdk.model.LocationResponse;
import com.jmalltech.gwms.sdk.model.LocationUpdateRequest;
import com.jmalltech.gwms.sdk.model.SortDirection;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class LocationsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public LocationsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public LocationsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createLocation
     * @param idempotencyKey 一个唯一的密钥（例如，UUID），以确保资源的幂等创建。 (required)
     * @param locationCreateRequest 要创建的库位信息。 (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> 库位已成功创建。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> 冲突。当请求与服务器的当前状态冲突时，将发送此响应。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createLocationCall(UUID idempotencyKey, LocationCreateRequest locationCreateRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = locationCreateRequest;

        // create path and map variables
        String localVarPath = "/api/v1/locations";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (idempotencyKey != null) {
            localVarHeaderParams.put("Idempotency-Key", localVarApiClient.parameterToString(idempotencyKey));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createLocationValidateBeforeCall(UUID idempotencyKey, LocationCreateRequest locationCreateRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'idempotencyKey' is set
        if (idempotencyKey == null) {
            throw new ApiException("Missing the required parameter 'idempotencyKey' when calling createLocation(Async)");
        }

        // verify the required parameter 'locationCreateRequest' is set
        if (locationCreateRequest == null) {
            throw new ApiException("Missing the required parameter 'locationCreateRequest' when calling createLocation(Async)");
        }

        return createLocationCall(idempotencyKey, locationCreateRequest, _callback);

    }

    /**
     * 创建库位
     * 在指定库区中创建一个新库位。此操作是幂等的。  **所需权限：** &#x60;warehouse:write&#x60;  **使用场景：** - 仓库扩建时批量创建库位 - 系统初始化时导入库位数据 - 货架调整后创建新库位 
     * @param idempotencyKey 一个唯一的密钥（例如，UUID），以确保资源的幂等创建。 (required)
     * @param locationCreateRequest 要创建的库位信息。 (required)
     * @return LocationResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> 库位已成功创建。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> 冲突。当请求与服务器的当前状态冲突时，将发送此响应。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public LocationResponse createLocation(UUID idempotencyKey, LocationCreateRequest locationCreateRequest) throws ApiException {
        ApiResponse<LocationResponse> localVarResp = createLocationWithHttpInfo(idempotencyKey, locationCreateRequest);
        return localVarResp.getData();
    }

    /**
     * 创建库位
     * 在指定库区中创建一个新库位。此操作是幂等的。  **所需权限：** &#x60;warehouse:write&#x60;  **使用场景：** - 仓库扩建时批量创建库位 - 系统初始化时导入库位数据 - 货架调整后创建新库位 
     * @param idempotencyKey 一个唯一的密钥（例如，UUID），以确保资源的幂等创建。 (required)
     * @param locationCreateRequest 要创建的库位信息。 (required)
     * @return ApiResponse&lt;LocationResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> 库位已成功创建。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> 冲突。当请求与服务器的当前状态冲突时，将发送此响应。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<LocationResponse> createLocationWithHttpInfo( @NotNull UUID idempotencyKey,  @NotNull LocationCreateRequest locationCreateRequest) throws ApiException {
        okhttp3.Call localVarCall = createLocationValidateBeforeCall(idempotencyKey, locationCreateRequest, null);
        Type localVarReturnType = new TypeToken<LocationResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 创建库位 (asynchronously)
     * 在指定库区中创建一个新库位。此操作是幂等的。  **所需权限：** &#x60;warehouse:write&#x60;  **使用场景：** - 仓库扩建时批量创建库位 - 系统初始化时导入库位数据 - 货架调整后创建新库位 
     * @param idempotencyKey 一个唯一的密钥（例如，UUID），以确保资源的幂等创建。 (required)
     * @param locationCreateRequest 要创建的库位信息。 (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> 库位已成功创建。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> 冲突。当请求与服务器的当前状态冲突时，将发送此响应。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createLocationAsync(UUID idempotencyKey, LocationCreateRequest locationCreateRequest, final ApiCallback<LocationResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = createLocationValidateBeforeCall(idempotencyKey, locationCreateRequest, _callback);
        Type localVarReturnType = new TypeToken<LocationResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getLocationByCode
     * @param code 库位编码。 (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 库位详情。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 未找到。服务器找不到请求的资源。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getLocationByCodeCall(String code, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/locations/code/{code}"
            .replace("{" + "code" + "}", localVarApiClient.escapeString(code.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getLocationByCodeValidateBeforeCall(String code, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'code' is set
        if (code == null) {
            throw new ApiException("Missing the required parameter 'code' when calling getLocationByCode(Async)");
        }

        return getLocationByCodeCall(code, _callback);

    }

    /**
     * 获取库位详情
     * 通过库位编码检索特定库位的详细信息。  **所需权限：** &#x60;warehouse:read&#x60;  **使用场景：** - 验证库位编码有效性 - 获取库位容量和规格信息 - 库存操作前查询库位状态 
     * @param code 库位编码。 (required)
     * @return LocationResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 库位详情。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 未找到。服务器找不到请求的资源。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public LocationResponse getLocationByCode(String code) throws ApiException {
        ApiResponse<LocationResponse> localVarResp = getLocationByCodeWithHttpInfo(code);
        return localVarResp.getData();
    }

    /**
     * 获取库位详情
     * 通过库位编码检索特定库位的详细信息。  **所需权限：** &#x60;warehouse:read&#x60;  **使用场景：** - 验证库位编码有效性 - 获取库位容量和规格信息 - 库存操作前查询库位状态 
     * @param code 库位编码。 (required)
     * @return ApiResponse&lt;LocationResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 库位详情。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 未找到。服务器找不到请求的资源。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<LocationResponse> getLocationByCodeWithHttpInfo( @NotNull String code) throws ApiException {
        okhttp3.Call localVarCall = getLocationByCodeValidateBeforeCall(code, null);
        Type localVarReturnType = new TypeToken<LocationResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 获取库位详情 (asynchronously)
     * 通过库位编码检索特定库位的详细信息。  **所需权限：** &#x60;warehouse:read&#x60;  **使用场景：** - 验证库位编码有效性 - 获取库位容量和规格信息 - 库存操作前查询库位状态 
     * @param code 库位编码。 (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 库位详情。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 未找到。服务器找不到请求的资源。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getLocationByCodeAsync(String code, final ApiCallback<LocationResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getLocationByCodeValidateBeforeCall(code, _callback);
        Type localVarReturnType = new TypeToken<LocationResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listLocations
     * @param pageNumber 页码（从1开始） (optional, default to 1)
     * @param pageSize 每页记录数 (optional, default to 20)
     * @param sort 结果的排序字段。使用逗号分隔的字段列表。 (optional)
     * @param isAsc 排序方向。ASC为升序，DESC为降序。 (optional)
     * @param warehouseId 按所属仓库ID筛选。 (optional)
     * @param zoneId 按所属库区ID筛选。 (optional)
     * @param code 按库位编码筛选。 (optional)
     * @param status 按库位状态筛选。 (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 库位的分页列表。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listLocationsCall(Integer pageNumber, Integer pageSize, String sort, SortDirection isAsc, Long warehouseId, Long zoneId, String code, EntityStatus status, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/locations";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (pageNumber != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("pageNumber", pageNumber));
        }

        if (pageSize != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("pageSize", pageSize));
        }

        if (sort != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sort", sort));
        }

        if (isAsc != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("isAsc", isAsc));
        }

        if (warehouseId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("warehouseId", warehouseId));
        }

        if (zoneId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("zoneId", zoneId));
        }

        if (code != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("code", code));
        }

        if (status != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("status", status));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listLocationsValidateBeforeCall(Integer pageNumber, Integer pageSize, String sort, SortDirection isAsc, Long warehouseId, Long zoneId, String code, EntityStatus status, final ApiCallback _callback) throws ApiException {
        return listLocationsCall(pageNumber, pageSize, sort, isAsc, warehouseId, zoneId, code, status, _callback);

    }

    /**
     * 列出库位
     * 检索库位的分页列表，允许过滤和排序。  **所需权限：** &#x60;warehouse:read&#x60;  **使用场景：** - 查询可用库位进行库存分配 - 获取库位列表用于拣货路径规划 - 系统集成时同步库位信息 
     * @param pageNumber 页码（从1开始） (optional, default to 1)
     * @param pageSize 每页记录数 (optional, default to 20)
     * @param sort 结果的排序字段。使用逗号分隔的字段列表。 (optional)
     * @param isAsc 排序方向。ASC为升序，DESC为降序。 (optional)
     * @param warehouseId 按所属仓库ID筛选。 (optional)
     * @param zoneId 按所属库区ID筛选。 (optional)
     * @param code 按库位编码筛选。 (optional)
     * @param status 按库位状态筛选。 (optional)
     * @return LocationListResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 库位的分页列表。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public LocationListResponse listLocations(Integer pageNumber, Integer pageSize, String sort, SortDirection isAsc, Long warehouseId, Long zoneId, String code, EntityStatus status) throws ApiException {
        ApiResponse<LocationListResponse> localVarResp = listLocationsWithHttpInfo(pageNumber, pageSize, sort, isAsc, warehouseId, zoneId, code, status);
        return localVarResp.getData();
    }

    /**
     * 列出库位
     * 检索库位的分页列表，允许过滤和排序。  **所需权限：** &#x60;warehouse:read&#x60;  **使用场景：** - 查询可用库位进行库存分配 - 获取库位列表用于拣货路径规划 - 系统集成时同步库位信息 
     * @param pageNumber 页码（从1开始） (optional, default to 1)
     * @param pageSize 每页记录数 (optional, default to 20)
     * @param sort 结果的排序字段。使用逗号分隔的字段列表。 (optional)
     * @param isAsc 排序方向。ASC为升序，DESC为降序。 (optional)
     * @param warehouseId 按所属仓库ID筛选。 (optional)
     * @param zoneId 按所属库区ID筛选。 (optional)
     * @param code 按库位编码筛选。 (optional)
     * @param status 按库位状态筛选。 (optional)
     * @return ApiResponse&lt;LocationListResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 库位的分页列表。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<LocationListResponse> listLocationsWithHttpInfo( @Min(1)Integer pageNumber,  @Min(1) @Max(100)Integer pageSize, String sort, SortDirection isAsc, Long warehouseId, Long zoneId, String code, EntityStatus status) throws ApiException {
        okhttp3.Call localVarCall = listLocationsValidateBeforeCall(pageNumber, pageSize, sort, isAsc, warehouseId, zoneId, code, status, null);
        Type localVarReturnType = new TypeToken<LocationListResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 列出库位 (asynchronously)
     * 检索库位的分页列表，允许过滤和排序。  **所需权限：** &#x60;warehouse:read&#x60;  **使用场景：** - 查询可用库位进行库存分配 - 获取库位列表用于拣货路径规划 - 系统集成时同步库位信息 
     * @param pageNumber 页码（从1开始） (optional, default to 1)
     * @param pageSize 每页记录数 (optional, default to 20)
     * @param sort 结果的排序字段。使用逗号分隔的字段列表。 (optional)
     * @param isAsc 排序方向。ASC为升序，DESC为降序。 (optional)
     * @param warehouseId 按所属仓库ID筛选。 (optional)
     * @param zoneId 按所属库区ID筛选。 (optional)
     * @param code 按库位编码筛选。 (optional)
     * @param status 按库位状态筛选。 (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 库位的分页列表。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listLocationsAsync(Integer pageNumber, Integer pageSize, String sort, SortDirection isAsc, Long warehouseId, Long zoneId, String code, EntityStatus status, final ApiCallback<LocationListResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = listLocationsValidateBeforeCall(pageNumber, pageSize, sort, isAsc, warehouseId, zoneId, code, status, _callback);
        Type localVarReturnType = new TypeToken<LocationListResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateLocation
     * @param code 库位编码。 (required)
     * @param locationUpdateRequest 要更新的库位信息。 (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 库位已成功更新。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 未找到。服务器找不到请求的资源。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateLocationCall(String code, LocationUpdateRequest locationUpdateRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = locationUpdateRequest;

        // create path and map variables
        String localVarPath = "/api/v1/locations/code/{code}"
            .replace("{" + "code" + "}", localVarApiClient.escapeString(code.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateLocationValidateBeforeCall(String code, LocationUpdateRequest locationUpdateRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'code' is set
        if (code == null) {
            throw new ApiException("Missing the required parameter 'code' when calling updateLocation(Async)");
        }

        // verify the required parameter 'locationUpdateRequest' is set
        if (locationUpdateRequest == null) {
            throw new ApiException("Missing the required parameter 'locationUpdateRequest' when calling updateLocation(Async)");
        }

        return updateLocationCall(code, locationUpdateRequest, _callback);

    }

    /**
     * 更新库位
     * 更新特定库位的信息。  **所需权限：** &#x60;warehouse:write&#x60;  **使用场景：** - 调整库位容量和规格 - 更新库位类型和属性 - 同步货架调整后的库位变更 
     * @param code 库位编码。 (required)
     * @param locationUpdateRequest 要更新的库位信息。 (required)
     * @return LocationResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 库位已成功更新。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 未找到。服务器找不到请求的资源。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public LocationResponse updateLocation(String code, LocationUpdateRequest locationUpdateRequest) throws ApiException {
        ApiResponse<LocationResponse> localVarResp = updateLocationWithHttpInfo(code, locationUpdateRequest);
        return localVarResp.getData();
    }

    /**
     * 更新库位
     * 更新特定库位的信息。  **所需权限：** &#x60;warehouse:write&#x60;  **使用场景：** - 调整库位容量和规格 - 更新库位类型和属性 - 同步货架调整后的库位变更 
     * @param code 库位编码。 (required)
     * @param locationUpdateRequest 要更新的库位信息。 (required)
     * @return ApiResponse&lt;LocationResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 库位已成功更新。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 未找到。服务器找不到请求的资源。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<LocationResponse> updateLocationWithHttpInfo( @NotNull String code,  @NotNull LocationUpdateRequest locationUpdateRequest) throws ApiException {
        okhttp3.Call localVarCall = updateLocationValidateBeforeCall(code, locationUpdateRequest, null);
        Type localVarReturnType = new TypeToken<LocationResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 更新库位 (asynchronously)
     * 更新特定库位的信息。  **所需权限：** &#x60;warehouse:write&#x60;  **使用场景：** - 调整库位容量和规格 - 更新库位类型和属性 - 同步货架调整后的库位变更 
     * @param code 库位编码。 (required)
     * @param locationUpdateRequest 要更新的库位信息。 (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 库位已成功更新。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 未找到。服务器找不到请求的资源。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateLocationAsync(String code, LocationUpdateRequest locationUpdateRequest, final ApiCallback<LocationResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateLocationValidateBeforeCall(code, locationUpdateRequest, _callback);
        Type localVarReturnType = new TypeToken<LocationResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateLocationStatus
     * @param code 库位编码。 (required)
     * @param status 新的库位状态。 (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 库位状态已成功更新。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 未找到。服务器找不到请求的资源。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateLocationStatusCall(String code, EntityStatus status, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/locations/code/{code}/status"
            .replace("{" + "code" + "}", localVarApiClient.escapeString(code.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (status != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("status", status));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateLocationStatusValidateBeforeCall(String code, EntityStatus status, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'code' is set
        if (code == null) {
            throw new ApiException("Missing the required parameter 'code' when calling updateLocationStatus(Async)");
        }

        // verify the required parameter 'status' is set
        if (status == null) {
            throw new ApiException("Missing the required parameter 'status' when calling updateLocationStatus(Async)");
        }

        return updateLocationStatusCall(code, status, _callback);

    }

    /**
     * 更新库位状态
     * 启用或禁用特定库位。  **所需权限：** &#x60;warehouse:write&#x60;  **使用场景：** - 库位维护时临时禁用 - 新库位投入使用时启用 - 库存策略调整时控制库位可用性 
     * @param code 库位编码。 (required)
     * @param status 新的库位状态。 (required)
     * @return LocationResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 库位状态已成功更新。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 未找到。服务器找不到请求的资源。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public LocationResponse updateLocationStatus(String code, EntityStatus status) throws ApiException {
        ApiResponse<LocationResponse> localVarResp = updateLocationStatusWithHttpInfo(code, status);
        return localVarResp.getData();
    }

    /**
     * 更新库位状态
     * 启用或禁用特定库位。  **所需权限：** &#x60;warehouse:write&#x60;  **使用场景：** - 库位维护时临时禁用 - 新库位投入使用时启用 - 库存策略调整时控制库位可用性 
     * @param code 库位编码。 (required)
     * @param status 新的库位状态。 (required)
     * @return ApiResponse&lt;LocationResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 库位状态已成功更新。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 未找到。服务器找不到请求的资源。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<LocationResponse> updateLocationStatusWithHttpInfo( @NotNull String code,  @NotNull EntityStatus status) throws ApiException {
        okhttp3.Call localVarCall = updateLocationStatusValidateBeforeCall(code, status, null);
        Type localVarReturnType = new TypeToken<LocationResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 更新库位状态 (asynchronously)
     * 启用或禁用特定库位。  **所需权限：** &#x60;warehouse:write&#x60;  **使用场景：** - 库位维护时临时禁用 - 新库位投入使用时启用 - 库存策略调整时控制库位可用性 
     * @param code 库位编码。 (required)
     * @param status 新的库位状态。 (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 库位状态已成功更新。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 未找到。服务器找不到请求的资源。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateLocationStatusAsync(String code, EntityStatus status, final ApiCallback<LocationResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateLocationStatusValidateBeforeCall(code, status, _callback);
        Type localVarReturnType = new TypeToken<LocationResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
