/*
 * GWMS Public API
 * GWMS（仓库管理系统）的官方公开API。 它为ERP、电子商务平台和TMS等外部系统提供了一个标准化、健壮且易于集成的接口，以便与WMS功能进行交互。  ## 认证机制  本API采用基于JWT的Bearer令牌认证，结合三重凭证验证机制：  1. **客户端凭证（Client Credentials）**：由系统管理员为上游系统生成的clientId和clientSecret 2. **API密钥（API Key）**：由仓库用户生成，关联到特定仓库和权限范围 3. **访问令牌（Access Token）**：通过认证端点获取的JWT令牌，用于API访问  ## 快速开始  1. **获取凭证**：联系系统管理员获取clientId和clientSecret，联系仓库用户获取apiKey 2. **获取令牌**：调用 `POST /auth-api/token` 端点获取访问令牌 3. **调用API**：在请求头中添加 `Authorization: Bearer {access_token}` 调用其他API  ## 认证头部格式  所有API请求（除了认证端点）必须包含以下HTTP头部：  ``` Authorization: Bearer {access_token} ```  其中`{access_token}`是从认证端点获取的JWT令牌。缺少此头部或令牌无效将导致401错误。  ## 权限范围  API访问权限基于以下范围进行控制：  | 权限范围 | 描述 | 适用API | 示例操作 | |---------|------|---------|---------| | `product:read` | 产品数据读取权限 | `/api/v1/products/_*` | 查询产品列表、获取产品详情 | | `product:write` | 产品数据写入权限 | `/api/v1/products/_*` | 创建产品、更新产品信息 | | `warehouse:read` | 仓库数据读取权限 | `/api/v1/warehouses/_*` | 查询仓库列表、获取仓库详情 | | `warehouse:write` | 仓库数据写入权限 | `/api/v1/warehouses/_*` | 创建仓库、更新仓库信息 | | `stock:read` | 库存数据读取权限 | `/api/v1/stock/_*` | 查询库存数量、库存明细 | | `stock:write` | 库存数据写入权限 | `/api/v1/stock/_*` | 库存调整、库存转移 | | `inbound:read` | 入库单读取权限 | `/api/v1/inbound/_*` | 查询入库单列表、获取入库单详情 | | `inbound:write` | 入库单写入权限 | `/api/v1/inbound/_*` | 创建入库单、更新入库单 | | `outbound:read` | 出库单读取权限 | `/api/v1/outbound/_*` | 查询出库单列表、获取出库单详情 | | `outbound:write` | 出库单写入权限 | `/api/v1/outbound/_*` | 创建出库单、更新出库单 | | `express:read` | 物流渠道读取权限 | `/api/v1/expressChannel/_*` | 查询物流渠道列表 | | `express:write` | 物流渠道写入权限 | `/api/v1/expressChannel/_*` | 创建物流渠道、更新物流渠道 |  ## 错误响应  认证失败时，API将返回以下错误响应：  - **401 Unauthorized**：令牌无效、过期或缺失 - **403 Forbidden**：令牌有效但权限不足 - **429 Too Many Requests**：超过访问频率限制  详细的错误响应格式请参考错误响应部分。 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: api-support@jmalltech.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.jmalltech.gwms.sdk.api;

import com.jmalltech.gwms.sdk.invoker.ApiCallback;
import com.jmalltech.gwms.sdk.invoker.ApiClient;
import com.jmalltech.gwms.sdk.invoker.ApiException;
import com.jmalltech.gwms.sdk.invoker.ApiResponse;
import com.jmalltech.gwms.sdk.invoker.Configuration;
import com.jmalltech.gwms.sdk.invoker.Pair;
import com.jmalltech.gwms.sdk.invoker.ProgressRequestBody;
import com.jmalltech.gwms.sdk.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;

import javax.validation.constraints.*;
import javax.validation.Valid;

import com.jmalltech.gwms.sdk.model.ApiErrorResponse;
import com.jmalltech.gwms.sdk.model.ProductSpuCreateRequest;
import com.jmalltech.gwms.sdk.model.ProductSpuListResponse;
import com.jmalltech.gwms.sdk.model.ProductSpuResponse;
import com.jmalltech.gwms.sdk.model.ProductSpuUpdateRequest;
import com.jmalltech.gwms.sdk.model.SortDirection;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ProductSpusApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ProductSpusApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ProductSpusApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createProductSpu
     * @param idempotencyKey 一个唯一的密钥（例如，UUID），以确保资源的幂等创建。 (required)
     * @param productSpuCreateRequest 要创建的产品SPU。 (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> 产品SPU已成功创建。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> 冲突。当请求与服务器的当前状态冲突时，将发送此响应。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createProductSpuCall(UUID idempotencyKey, ProductSpuCreateRequest productSpuCreateRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = productSpuCreateRequest;

        // create path and map variables
        String localVarPath = "/api/v1/products/spus";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (idempotencyKey != null) {
            localVarHeaderParams.put("Idempotency-Key", localVarApiClient.parameterToString(idempotencyKey));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createProductSpuValidateBeforeCall(UUID idempotencyKey, ProductSpuCreateRequest productSpuCreateRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'idempotencyKey' is set
        if (idempotencyKey == null) {
            throw new ApiException("Missing the required parameter 'idempotencyKey' when calling createProductSpu(Async)");
        }

        // verify the required parameter 'productSpuCreateRequest' is set
        if (productSpuCreateRequest == null) {
            throw new ApiException("Missing the required parameter 'productSpuCreateRequest' when calling createProductSpu(Async)");
        }

        return createProductSpuCall(idempotencyKey, productSpuCreateRequest, _callback);

    }

    /**
     * 创建一个产品SPU
     * 在主数据中创建一个新的产品SPU。此操作是幂等的，支持上游系统推送产品SPU数据。
     * @param idempotencyKey 一个唯一的密钥（例如，UUID），以确保资源的幂等创建。 (required)
     * @param productSpuCreateRequest 要创建的产品SPU。 (required)
     * @return ProductSpuResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> 产品SPU已成功创建。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> 冲突。当请求与服务器的当前状态冲突时，将发送此响应。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public ProductSpuResponse createProductSpu(UUID idempotencyKey, ProductSpuCreateRequest productSpuCreateRequest) throws ApiException {
        ApiResponse<ProductSpuResponse> localVarResp = createProductSpuWithHttpInfo(idempotencyKey, productSpuCreateRequest);
        return localVarResp.getData();
    }

    /**
     * 创建一个产品SPU
     * 在主数据中创建一个新的产品SPU。此操作是幂等的，支持上游系统推送产品SPU数据。
     * @param idempotencyKey 一个唯一的密钥（例如，UUID），以确保资源的幂等创建。 (required)
     * @param productSpuCreateRequest 要创建的产品SPU。 (required)
     * @return ApiResponse&lt;ProductSpuResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> 产品SPU已成功创建。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> 冲突。当请求与服务器的当前状态冲突时，将发送此响应。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ProductSpuResponse> createProductSpuWithHttpInfo( @NotNull UUID idempotencyKey,  @NotNull ProductSpuCreateRequest productSpuCreateRequest) throws ApiException {
        okhttp3.Call localVarCall = createProductSpuValidateBeforeCall(idempotencyKey, productSpuCreateRequest, null);
        Type localVarReturnType = new TypeToken<ProductSpuResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 创建一个产品SPU (asynchronously)
     * 在主数据中创建一个新的产品SPU。此操作是幂等的，支持上游系统推送产品SPU数据。
     * @param idempotencyKey 一个唯一的密钥（例如，UUID），以确保资源的幂等创建。 (required)
     * @param productSpuCreateRequest 要创建的产品SPU。 (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> 产品SPU已成功创建。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> 冲突。当请求与服务器的当前状态冲突时，将发送此响应。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createProductSpuAsync(UUID idempotencyKey, ProductSpuCreateRequest productSpuCreateRequest, final ApiCallback<ProductSpuResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = createProductSpuValidateBeforeCall(idempotencyKey, productSpuCreateRequest, _callback);
        Type localVarReturnType = new TypeToken<ProductSpuResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteProductSpuByCode
     * @param spuCode 产品SPU的业务编码。 (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> 产品SPU已成功删除。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 未找到。服务器找不到请求的资源。 </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> 冲突。产品SPU无法删除，例如，它有关联的产品。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteProductSpuByCodeCall(String spuCode, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/products/spus/code/{spuCode}"
            .replace("{" + "spuCode" + "}", localVarApiClient.escapeString(spuCode.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteProductSpuByCodeValidateBeforeCall(String spuCode, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'spuCode' is set
        if (spuCode == null) {
            throw new ApiException("Missing the required parameter 'spuCode' when calling deleteProductSpuByCode(Async)");
        }

        return deleteProductSpuByCodeCall(spuCode, _callback);

    }

    /**
     * 通过SPU编码删除产品SPU
     * 通过SPU编码删除产品SPU。使用业务编码而非内部ID进行操作。
     * @param spuCode 产品SPU的业务编码。 (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> 产品SPU已成功删除。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 未找到。服务器找不到请求的资源。 </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> 冲突。产品SPU无法删除，例如，它有关联的产品。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public void deleteProductSpuByCode(String spuCode) throws ApiException {
        deleteProductSpuByCodeWithHttpInfo(spuCode);
    }

    /**
     * 通过SPU编码删除产品SPU
     * 通过SPU编码删除产品SPU。使用业务编码而非内部ID进行操作。
     * @param spuCode 产品SPU的业务编码。 (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> 产品SPU已成功删除。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 未找到。服务器找不到请求的资源。 </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> 冲突。产品SPU无法删除，例如，它有关联的产品。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> deleteProductSpuByCodeWithHttpInfo( @NotNull  @Pattern(regexp="^[A-Za-z0-9-]{1,50}$")String spuCode) throws ApiException {
        okhttp3.Call localVarCall = deleteProductSpuByCodeValidateBeforeCall(spuCode, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * 通过SPU编码删除产品SPU (asynchronously)
     * 通过SPU编码删除产品SPU。使用业务编码而非内部ID进行操作。
     * @param spuCode 产品SPU的业务编码。 (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> 产品SPU已成功删除。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 未找到。服务器找不到请求的资源。 </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> 冲突。产品SPU无法删除，例如，它有关联的产品。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteProductSpuByCodeAsync(String spuCode, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteProductSpuByCodeValidateBeforeCall(spuCode, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for getProductSpuByCode
     * @param spuCode 产品SPU的业务编码。 (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 产品SPU详情。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 未找到。服务器找不到请求的资源。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getProductSpuByCodeCall(String spuCode, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/products/spus/code/{spuCode}"
            .replace("{" + "spuCode" + "}", localVarApiClient.escapeString(spuCode.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getProductSpuByCodeValidateBeforeCall(String spuCode, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'spuCode' is set
        if (spuCode == null) {
            throw new ApiException("Missing the required parameter 'spuCode' when calling getProductSpuByCode(Async)");
        }

        return getProductSpuByCodeCall(spuCode, _callback);

    }

    /**
     * 通过SPU编码获取产品SPU
     * 通过SPU编码检索特定产品SPU的详细信息。使用业务编码而非内部ID进行查询。
     * @param spuCode 产品SPU的业务编码。 (required)
     * @return ProductSpuResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 产品SPU详情。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 未找到。服务器找不到请求的资源。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public ProductSpuResponse getProductSpuByCode(String spuCode) throws ApiException {
        ApiResponse<ProductSpuResponse> localVarResp = getProductSpuByCodeWithHttpInfo(spuCode);
        return localVarResp.getData();
    }

    /**
     * 通过SPU编码获取产品SPU
     * 通过SPU编码检索特定产品SPU的详细信息。使用业务编码而非内部ID进行查询。
     * @param spuCode 产品SPU的业务编码。 (required)
     * @return ApiResponse&lt;ProductSpuResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 产品SPU详情。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 未找到。服务器找不到请求的资源。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ProductSpuResponse> getProductSpuByCodeWithHttpInfo( @NotNull  @Pattern(regexp="^[A-Za-z0-9-]{1,50}$")String spuCode) throws ApiException {
        okhttp3.Call localVarCall = getProductSpuByCodeValidateBeforeCall(spuCode, null);
        Type localVarReturnType = new TypeToken<ProductSpuResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 通过SPU编码获取产品SPU (asynchronously)
     * 通过SPU编码检索特定产品SPU的详细信息。使用业务编码而非内部ID进行查询。
     * @param spuCode 产品SPU的业务编码。 (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 产品SPU详情。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 未找到。服务器找不到请求的资源。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getProductSpuByCodeAsync(String spuCode, final ApiCallback<ProductSpuResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getProductSpuByCodeValidateBeforeCall(spuCode, _callback);
        Type localVarReturnType = new TypeToken<ProductSpuResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listProductSpus
     * @param pageNumber 页码（从1开始） (optional, default to 1)
     * @param pageSize 每页记录数 (optional, default to 20)
     * @param sort 结果的排序字段。使用逗号分隔的字段列表。 (optional)
     * @param isAsc 排序方向。ASC为升序，DESC为降序。 (optional)
     * @param spuCode 按SPU编码筛选。 (optional)
     * @param productName 按产品名称筛选。 (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 产品SPU的分页列表。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listProductSpusCall(Integer pageNumber, Integer pageSize, String sort, SortDirection isAsc, String spuCode, String productName, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/products/spus";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (pageNumber != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("pageNumber", pageNumber));
        }

        if (pageSize != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("pageSize", pageSize));
        }

        if (sort != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sort", sort));
        }

        if (isAsc != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("isAsc", isAsc));
        }

        if (spuCode != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("spuCode", spuCode));
        }

        if (productName != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("productName", productName));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listProductSpusValidateBeforeCall(Integer pageNumber, Integer pageSize, String sort, SortDirection isAsc, String spuCode, String productName, final ApiCallback _callback) throws ApiException {
        return listProductSpusCall(pageNumber, pageSize, sort, isAsc, spuCode, productName, _callback);

    }

    /**
     * 列出产品SPU
     * 检索产品SPU的分页列表，允许过滤和排序。
     * @param pageNumber 页码（从1开始） (optional, default to 1)
     * @param pageSize 每页记录数 (optional, default to 20)
     * @param sort 结果的排序字段。使用逗号分隔的字段列表。 (optional)
     * @param isAsc 排序方向。ASC为升序，DESC为降序。 (optional)
     * @param spuCode 按SPU编码筛选。 (optional)
     * @param productName 按产品名称筛选。 (optional)
     * @return ProductSpuListResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 产品SPU的分页列表。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public ProductSpuListResponse listProductSpus(Integer pageNumber, Integer pageSize, String sort, SortDirection isAsc, String spuCode, String productName) throws ApiException {
        ApiResponse<ProductSpuListResponse> localVarResp = listProductSpusWithHttpInfo(pageNumber, pageSize, sort, isAsc, spuCode, productName);
        return localVarResp.getData();
    }

    /**
     * 列出产品SPU
     * 检索产品SPU的分页列表，允许过滤和排序。
     * @param pageNumber 页码（从1开始） (optional, default to 1)
     * @param pageSize 每页记录数 (optional, default to 20)
     * @param sort 结果的排序字段。使用逗号分隔的字段列表。 (optional)
     * @param isAsc 排序方向。ASC为升序，DESC为降序。 (optional)
     * @param spuCode 按SPU编码筛选。 (optional)
     * @param productName 按产品名称筛选。 (optional)
     * @return ApiResponse&lt;ProductSpuListResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 产品SPU的分页列表。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ProductSpuListResponse> listProductSpusWithHttpInfo( @Min(1)Integer pageNumber,  @Min(1) @Max(100)Integer pageSize, String sort, SortDirection isAsc, String spuCode, String productName) throws ApiException {
        okhttp3.Call localVarCall = listProductSpusValidateBeforeCall(pageNumber, pageSize, sort, isAsc, spuCode, productName, null);
        Type localVarReturnType = new TypeToken<ProductSpuListResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 列出产品SPU (asynchronously)
     * 检索产品SPU的分页列表，允许过滤和排序。
     * @param pageNumber 页码（从1开始） (optional, default to 1)
     * @param pageSize 每页记录数 (optional, default to 20)
     * @param sort 结果的排序字段。使用逗号分隔的字段列表。 (optional)
     * @param isAsc 排序方向。ASC为升序，DESC为降序。 (optional)
     * @param spuCode 按SPU编码筛选。 (optional)
     * @param productName 按产品名称筛选。 (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 产品SPU的分页列表。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listProductSpusAsync(Integer pageNumber, Integer pageSize, String sort, SortDirection isAsc, String spuCode, String productName, final ApiCallback<ProductSpuListResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = listProductSpusValidateBeforeCall(pageNumber, pageSize, sort, isAsc, spuCode, productName, _callback);
        Type localVarReturnType = new TypeToken<ProductSpuListResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateProductSpuByCode
     * @param spuCode 产品SPU的业务编码。 (required)
     * @param productSpuUpdateRequest 要更新的完整产品SPU数据。 (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 产品SPU已成功更新。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 未找到。服务器找不到请求的资源。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateProductSpuByCodeCall(String spuCode, ProductSpuUpdateRequest productSpuUpdateRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = productSpuUpdateRequest;

        // create path and map variables
        String localVarPath = "/api/v1/products/spus/code/{spuCode}"
            .replace("{" + "spuCode" + "}", localVarApiClient.escapeString(spuCode.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateProductSpuByCodeValidateBeforeCall(String spuCode, ProductSpuUpdateRequest productSpuUpdateRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'spuCode' is set
        if (spuCode == null) {
            throw new ApiException("Missing the required parameter 'spuCode' when calling updateProductSpuByCode(Async)");
        }

        // verify the required parameter 'productSpuUpdateRequest' is set
        if (productSpuUpdateRequest == null) {
            throw new ApiException("Missing the required parameter 'productSpuUpdateRequest' when calling updateProductSpuByCode(Async)");
        }

        return updateProductSpuByCodeCall(spuCode, productSpuUpdateRequest, _callback);

    }

    /**
     * 通过SPU编码更新产品SPU（完整）
     * 通过SPU编码更新产品SPU的所有属性。使用业务编码而非内部ID进行操作。
     * @param spuCode 产品SPU的业务编码。 (required)
     * @param productSpuUpdateRequest 要更新的完整产品SPU数据。 (required)
     * @return ProductSpuResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 产品SPU已成功更新。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 未找到。服务器找不到请求的资源。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public ProductSpuResponse updateProductSpuByCode(String spuCode, ProductSpuUpdateRequest productSpuUpdateRequest) throws ApiException {
        ApiResponse<ProductSpuResponse> localVarResp = updateProductSpuByCodeWithHttpInfo(spuCode, productSpuUpdateRequest);
        return localVarResp.getData();
    }

    /**
     * 通过SPU编码更新产品SPU（完整）
     * 通过SPU编码更新产品SPU的所有属性。使用业务编码而非内部ID进行操作。
     * @param spuCode 产品SPU的业务编码。 (required)
     * @param productSpuUpdateRequest 要更新的完整产品SPU数据。 (required)
     * @return ApiResponse&lt;ProductSpuResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 产品SPU已成功更新。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 未找到。服务器找不到请求的资源。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ProductSpuResponse> updateProductSpuByCodeWithHttpInfo( @NotNull  @Pattern(regexp="^[A-Za-z0-9-]{1,50}$")String spuCode,  @NotNull ProductSpuUpdateRequest productSpuUpdateRequest) throws ApiException {
        okhttp3.Call localVarCall = updateProductSpuByCodeValidateBeforeCall(spuCode, productSpuUpdateRequest, null);
        Type localVarReturnType = new TypeToken<ProductSpuResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 通过SPU编码更新产品SPU（完整） (asynchronously)
     * 通过SPU编码更新产品SPU的所有属性。使用业务编码而非内部ID进行操作。
     * @param spuCode 产品SPU的业务编码。 (required)
     * @param productSpuUpdateRequest 要更新的完整产品SPU数据。 (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 产品SPU已成功更新。 </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> 错误的请求。由于被认为是客户端错误（例如，格式错误的请求语法、无效的请求消息帧或欺骗性的请求路由），服务器无法或不会处理该请求。 </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> 未经授权。客户端必须对自己进行身份验证才能获得请求的响应。 </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> 未找到。服务器找不到请求的资源。 </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> 内部服务器错误。服务器遇到了不知道如何处理的情况。 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateProductSpuByCodeAsync(String spuCode, ProductSpuUpdateRequest productSpuUpdateRequest, final ApiCallback<ProductSpuResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateProductSpuByCodeValidateBeforeCall(spuCode, productSpuUpdateRequest, _callback);
        Type localVarReturnType = new TypeToken<ProductSpuResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
